spring.application.name=worksphere

#MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=WorkSphere

# JWT Secret Key (must be Base64 encoded, min 256 bits)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXP_TIME}

# Attendance rules
attendance.standard-hours=8
attendance.half-day-hours=4
attendance.work-start-time=10:00
attendance.grace-period-minutes=15

#Jackson Timezone
spring.jackson.time-zone=Asia/Kolkata
spring.jackson.serialization.write-dates-as-timestamps=false

# Your Mail trap Credentials
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Technical Settings (The "tls = yes" part)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Sender email
spring.mail.from=${EMAIL}

#App
app.base-url=http://localhost:8080

#Environment
spring.profiles.active=local

