spring.application.name=worksphere

spring.data.mongodb.uri=mongodb+srv://harshkumar0614jain_db_user:pvmLsnefdFNHCjIS@cluster0.kifdxr3.mongodb.net/WorkSphere?appName=Cluster0
spring.data.mongodb.database=WorkSphere

# JWT Secret Key (must be Base64 encoded, min 256 bits)
jwt.secret=V29ya1NwaGVyZUAyMDI0I0hhcnNoS3VtYXIkU2VjcmV0S2V5IUpXVEBTZWN1cmU4MzE5MDkwNzM2
jwt.expiration=1800000
# 1800000ms = 30 minutes

# Keep true during development, set false in production
spring.data.mongodb.auto-index-creation=true

# Remove these two — only needed during debugging
# logging.level.org.springframework.data.mongodb=DEBUG
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


